# baseURL
baseURL = "/hugoworkshop/"
languageCode = "en-US"
defaultContentLanguage = "en"

# title
title = "Making hugo based hands on lab site"
theme = "hugo-theme-learn"
themesdir = "."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
ignoreFiles = []

# description, author
[params]
  description = "Description"
  author = "Author Name"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages.en]
title = ""
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits/"
weight = 30
